/*
  Simple DirectMedia Layer
  Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

package com.hiczp.factorio.mcp

/** Adapted from SDL2's public SDL_Scancode enum. These are SDK constants, never game object offsets.
 * https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_scancode.h
 * Platform adapters must independently establish the typed native scancode field before using these values.
 */
internal object SdlScancodes {
    val codes: Map<String, UInt> = mapOf(
        "A" to 4u,
        "B" to 5u,
        "C" to 6u,
        "D" to 7u,
        "E" to 8u,
        "F" to 9u,
        "G" to 10u,
        "H" to 11u,
        "I" to 12u,
        "J" to 13u,
        "K" to 14u,
        "L" to 15u,
        "M" to 16u,
        "N" to 17u,
        "O" to 18u,
        "P" to 19u,
        "Q" to 20u,
        "R" to 21u,
        "S" to 22u,
        "T" to 23u,
        "U" to 24u,
        "V" to 25u,
        "W" to 26u,
        "X" to 27u,
        "Y" to 28u,
        "Z" to 29u,
        "1" to 30u,
        "2" to 31u,
        "3" to 32u,
        "4" to 33u,
        "5" to 34u,
        "6" to 35u,
        "7" to 36u,
        "8" to 37u,
        "9" to 38u,
        "0" to 39u,
        "RETURN" to 40u,
        "ESCAPE" to 41u,
        "BACKSPACE" to 42u,
        "TAB" to 43u,
        "SPACE" to 44u,
        "MINUS" to 45u,
        "EQUALS" to 46u,
        "LEFTBRACKET" to 47u,
        "RIGHTBRACKET" to 48u,
        "BACKSLASH" to 49u,
        "NONUSHASH" to 50u,
        "SEMICOLON" to 51u,
        "APOSTROPHE" to 52u,
        "GRAVE" to 53u,
        "COMMA" to 54u,
        "PERIOD" to 55u,
        "SLASH" to 56u,
        "CAPSLOCK" to 57u,
        "F1" to 58u,
        "F2" to 59u,
        "F3" to 60u,
        "F4" to 61u,
        "F5" to 62u,
        "F6" to 63u,
        "F7" to 64u,
        "F8" to 65u,
        "F9" to 66u,
        "F10" to 67u,
        "F11" to 68u,
        "F12" to 69u,
        "PRINTSCREEN" to 70u,
        "SCROLLLOCK" to 71u,
        "PAUSE" to 72u,
        "INSERT" to 73u,
        "HOME" to 74u,
        "PAGEUP" to 75u,
        "DELETE" to 76u,
        "END" to 77u,
        "PAGEDOWN" to 78u,
        "RIGHT" to 79u,
        "LEFT" to 80u,
        "DOWN" to 81u,
        "UP" to 82u,
        "NUMLOCKCLEAR" to 83u,
        "KP_DIVIDE" to 84u,
        "KP_MULTIPLY" to 85u,
        "KP_MINUS" to 86u,
        "KP_PLUS" to 87u,
        "KP_ENTER" to 88u,
        "KP_1" to 89u,
        "KP_2" to 90u,
        "KP_3" to 91u,
        "KP_4" to 92u,
        "KP_5" to 93u,
        "KP_6" to 94u,
        "KP_7" to 95u,
        "KP_8" to 96u,
        "KP_9" to 97u,
        "KP_0" to 98u,
        "KP_PERIOD" to 99u,
        "NONUSBACKSLASH" to 100u,
        "APPLICATION" to 101u,
        "POWER" to 102u,
        "KP_EQUALS" to 103u,
        "F13" to 104u,
        "F14" to 105u,
        "F15" to 106u,
        "F16" to 107u,
        "F17" to 108u,
        "F18" to 109u,
        "F19" to 110u,
        "F20" to 111u,
        "F21" to 112u,
        "F22" to 113u,
        "F23" to 114u,
        "F24" to 115u,
        "EXECUTE" to 116u,
        "HELP" to 117u,
        "MENU" to 118u,
        "SELECT" to 119u,
        "STOP" to 120u,
        "AGAIN" to 121u,
        "UNDO" to 122u,
        "CUT" to 123u,
        "COPY" to 124u,
        "PASTE" to 125u,
        "FIND" to 126u,
        "MUTE" to 127u,
        "VOLUMEUP" to 128u,
        "VOLUMEDOWN" to 129u,
        "KP_COMMA" to 133u,
        "KP_EQUALSAS400" to 134u,
        "INTERNATIONAL1" to 135u,
        "INTERNATIONAL2" to 136u,
        "INTERNATIONAL3" to 137u,
        "INTERNATIONAL4" to 138u,
        "INTERNATIONAL5" to 139u,
        "INTERNATIONAL6" to 140u,
        "INTERNATIONAL7" to 141u,
        "INTERNATIONAL8" to 142u,
        "INTERNATIONAL9" to 143u,
        "LANG1" to 144u,
        "LANG2" to 145u,
        "LANG3" to 146u,
        "LANG4" to 147u,
        "LANG5" to 148u,
        "LANG6" to 149u,
        "LANG7" to 150u,
        "LANG8" to 151u,
        "LANG9" to 152u,
        "ALTERASE" to 153u,
        "SYSREQ" to 154u,
        "CANCEL" to 155u,
        "CLEAR" to 156u,
        "PRIOR" to 157u,
        "RETURN2" to 158u,
        "SEPARATOR" to 159u,
        "OUT" to 160u,
        "OPER" to 161u,
        "CLEARAGAIN" to 162u,
        "CRSEL" to 163u,
        "EXSEL" to 164u,
        "KP_00" to 176u,
        "KP_000" to 177u,
        "THOUSANDSSEPARATOR" to 178u,
        "DECIMALSEPARATOR" to 179u,
        "CURRENCYUNIT" to 180u,
        "CURRENCYSUBUNIT" to 181u,
        "KP_LEFTPAREN" to 182u,
        "KP_RIGHTPAREN" to 183u,
        "KP_LEFTBRACE" to 184u,
        "KP_RIGHTBRACE" to 185u,
        "KP_TAB" to 186u,
        "KP_BACKSPACE" to 187u,
        "KP_A" to 188u,
        "KP_B" to 189u,
        "KP_C" to 190u,
        "KP_D" to 191u,
        "KP_E" to 192u,
        "KP_F" to 193u,
        "KP_XOR" to 194u,
        "KP_POWER" to 195u,
        "KP_PERCENT" to 196u,
        "KP_LESS" to 197u,
        "KP_GREATER" to 198u,
        "KP_AMPERSAND" to 199u,
        "KP_DBLAMPERSAND" to 200u,
        "KP_VERTICALBAR" to 201u,
        "KP_DBLVERTICALBAR" to 202u,
        "KP_COLON" to 203u,
        "KP_HASH" to 204u,
        "KP_SPACE" to 205u,
        "KP_AT" to 206u,
        "KP_EXCLAM" to 207u,
        "KP_MEMSTORE" to 208u,
        "KP_MEMRECALL" to 209u,
        "KP_MEMCLEAR" to 210u,
        "KP_MEMADD" to 211u,
        "KP_MEMSUBTRACT" to 212u,
        "KP_MEMMULTIPLY" to 213u,
        "KP_MEMDIVIDE" to 214u,
        "KP_PLUSMINUS" to 215u,
        "KP_CLEAR" to 216u,
        "KP_CLEARENTRY" to 217u,
        "KP_BINARY" to 218u,
        "KP_OCTAL" to 219u,
        "KP_DECIMAL" to 220u,
        "KP_HEXADECIMAL" to 221u,
        "LCTRL" to 224u,
        "LSHIFT" to 225u,
        "LALT" to 226u,
        "LGUI" to 227u,
        "RCTRL" to 228u,
        "RSHIFT" to 229u,
        "RALT" to 230u,
        "RGUI" to 231u,
        "MODE" to 257u,
        "AUDIONEXT" to 258u,
        "AUDIOPREV" to 259u,
        "AUDIOSTOP" to 260u,
        "AUDIOPLAY" to 261u,
        "AUDIOMUTE" to 262u,
        "MEDIASELECT" to 263u,
        "WWW" to 264u,
        "MAIL" to 265u,
        "CALCULATOR" to 266u,
        "COMPUTER" to 267u,
        "AC_SEARCH" to 268u,
        "AC_HOME" to 269u,
        "AC_BACK" to 270u,
        "AC_FORWARD" to 271u,
        "AC_STOP" to 272u,
        "AC_REFRESH" to 273u,
        "AC_BOOKMARKS" to 274u,
        "BRIGHTNESSDOWN" to 275u,
        "BRIGHTNESSUP" to 276u,
        "DISPLAYSWITCH" to 277u,
        "KBDILLUMTOGGLE" to 278u,
        "KBDILLUMDOWN" to 279u,
        "KBDILLUMUP" to 280u,
        "EJECT" to 281u,
        "SLEEP" to 282u,
        "APP1" to 283u,
        "APP2" to 284u,
        "AUDIOREWIND" to 285u,
        "AUDIOFASTFORWARD" to 286u,
        "SOFTLEFT" to 287u,
        "SOFTRIGHT" to 288u,
        "CALL" to 289u,
        "ENDCALL" to 290u,
    )

    val names: Map<UInt, String> = codes.entries.associate { it.value to it.key }

    fun chord(names: List<String>): List<UInt> {
        require(names.size in 1..8) { "Invalid key chord size" }
        return names.map { codes[it] ?: error("Unknown key '$it'; use input_bindings key names") }.also {
            require(it.distinct().size == it.size) { "Key chord contains duplicate keys" }
        }
    }
}
