# Use the same Linux ABI as Kotlin/Native, including when building on Windows.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    KONAN_LLVM_HOME KONAN_GCC_TOOLCHAIN KONAN_SYSROOT KONAN_BINUTILS KONAN_TARGET_TRIPLE KONAN_LINKER)

foreach(variable KONAN_LLVM_HOME KONAN_GCC_TOOLCHAIN KONAN_SYSROOT KONAN_BINUTILS KONAN_TARGET_TRIPLE KONAN_LINKER)
    if(NOT DEFINED ${variable})
        message(FATAL_ERROR "${variable} is required; configure through Gradle")
    endif()
    file(TO_CMAKE_PATH "${${variable}}" ${variable})
endforeach()

if(CMAKE_HOST_WIN32)
    set(tool_suffix .exe)
else()
    set(tool_suffix "")
endif()

set(CMAKE_SYSROOT "${KONAN_SYSROOT}")
set(CMAKE_C_COMPILER "${KONAN_LLVM_HOME}/bin/clang${tool_suffix}")
set(CMAKE_CXX_COMPILER "${KONAN_LLVM_HOME}/bin/clang++${tool_suffix}")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
foreach(language C CXX ASM)
    set(CMAKE_${language}_COMPILER_TARGET "${KONAN_TARGET_TRIPLE}")
endforeach()
foreach(language C CXX)
    set(CMAKE_${language}_COMPILER_EXTERNAL_TOOLCHAIN "${KONAN_GCC_TOOLCHAIN}")
endforeach()
set(CMAKE_EXE_LINKER_FLAGS_INIT "--ld-path=\"${KONAN_LINKER}\"")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "--ld-path=\"${KONAN_LINKER}\"")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "--ld-path=\"${KONAN_LINKER}\"")
set(CMAKE_AR "${KONAN_LLVM_HOME}/bin/llvm-ar${tool_suffix}")
foreach(tool NM OBJCOPY RANLIB)
    string(TOLOWER "${tool}" tool_name)
    find_program(CMAKE_${tool} NAMES "${tool_name}${tool_suffix}"
        PATHS "${KONAN_BINUTILS}/bin" NO_DEFAULT_PATH REQUIRED)
endforeach()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
