package com.hiczp.factorio.mcp.buildlogic

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeSpec
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateBuildVersion : DefaultTask() {
    @get:Input
    abstract val releaseVersion: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val versionType =
            TypeSpec.objectBuilder("BuildVersion")
                .addModifiers(KModifier.INTERNAL)
                .addProperty(
                    PropertySpec.builder("VERSION", STRING, KModifier.CONST)
                        .initializer("%S", releaseVersion.get())
                        .build()
                )
                .build()

        FileSpec.builder("com.hiczp.factorio.mcp", "BuildVersion")
            .addFileComment("Generated by generateBuildVersion. Do not edit.")
            .indent("    ")
            .addType(versionType)
            .build()
            .writeTo(outputDirectory.get().asFile)
    }
}
